### ISSUE TITLE
J6/J7 - round pad seems slightly smaller 

### ISSUE THREAD

**Issue by hexbus** [hackup/C128Diag#2]
First - thank you for the excellent build.  I have it all working except the harnesses, which I'm working on.  I have been trying to obtain some removable pin headers that fit, and, in the process, noticed that all the jumper harness holes are 1.0mm except the round pads on J6/J7.  Those appear to be 0.75mm or so.  Was this intentional to make these two round pads smaller?  

If not, consider this something that I found as I was trying to fit a square pin into a round hole ;)

Thank you!

**Comment by hackup** [comment]
Indeed, you are right. For J6 and J7 the hole diameter of pin 1 and 2 is actually different. This was not intentional and I didn't notice it because I soldered the wires directly to the board like the original. I will fix this, but it doesn't warrant a new board revision by itself in my opinion.

**Comment by hexbus** [comment]
No problem, thanks for fixing it!  I will likely use normal pin headers for those two jacks for now.  I’m trying to keep my harnesses removable, and will just have two DuPont connectors on those.
